name: Checkmarx AST Github Actions
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@main
        with:
          base_uri: https://ast.checkmarx.net
          github_token: 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
          cx_tenant: dp_wp_na
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          project_name: ${{ github.repository }}
          #branch: ${{ github.head_ref }}
          additional_params: --scan-types sast


