name: Checkmarx AST Github Action
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@main
        with:
          base_uri: https://ast.checkmarx.net
          github_token: ${{ github.token }}
          cx_tenant: cx_se_andrew_schmit
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          project_name: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref }}
          additional_params: --scan-types sast


